### ISSUE TITLE
[discuss]关于压测设计的一点想法

### ISSUE THREAD

**Issue by anjia0532** [dragonflyoss/perf-tests#1]
我认为 d7y 主要用于 文件下载 和 镜像下载 ，如果使用传统接口压测工具，类似 [k6](https://k6.io/), [wrk](https://github.com/wg/wrk),[gatling](https://gatling.io/) 等工具来压测接口性能（比如http proxy？）并不是很贴合使用场景

而且这些压测工具有点像加特林，从固定几个点位去扫一大片。而实际使用场景，应该是一大片(上千dfdaemon/dfget)来攻击几个点(cdn/schedule)

所以我设想的压测方案是 深度依赖 k8s .

- 调度部分依赖k8s的scale，选择器+亲和性和污点+容忍，比如压测规模是400节点还是800节点,由 scale来做，哪些节点是高性能哪些是弱节点由节点标签来指定，在压测时使用选择器+亲和性来做
- 针对集团冲锋火力集束部分，依赖扩容完的pod内的cronjob(注意不是k8s的cronjob,也不是k8s物理机的cronjob)+主机ntp校时来做，能够实现秒或者毫秒级误差，避免火力分散(如果由自己编写的压测可能存在主控节点下发不及时等问题)
- 压测指标评估部分用 Metrics(可能需要完善) + Prometheus + Grafana(目前没有 dashboard 未开源) + Node exporter（cpu，内存，磁盘，带宽，等） + Redis exporter + Mysql exporter
- 压测任务 summary 部分由 日志（可能需要完善） +Filebeat/Fluentd 上报到ES/Loki/Clickhouse 然后执行 query 来查询，成功多少，失败多少，p99多少，长尾多少
- 压测工具的维护量极低（只相当于一个翻译器/配置器的工作，其余工作交给k8s或者其他组件）
- 审计友好(都是 yaml )，版本管理友好(配合git)，可读性好(会读 k8s yaml 就能看懂)
- 如果不想走统一日志的话，还可以给pod挂共享存储，比如nfs或者nas，这样可以用于回溯问题

这么一来 压测工具的工作就很简单了，技术点从压测逻辑/观测逻辑 脱离开，只关心，压测任务的配置及转换成 helm 的 values.yaml (helm install ), 或者也可以直接是 k8s 的 yaml( kubectl apply -f)

**Comment by qwtsc** [comment]
简单评论下：1. apiserver只要做到高可用就不会存在下发不及时问题 2. dashboard已有内部版本，压测summary建议直接读metrics，而不是分析日志 3. 我建议直接搞个k8s job在集群里访问apiserver下发dfget命令即可，由该job镜像来做metric收集和后续dingding通知，维护的话维护一个job镜像即可

**Comment by anjia0532** [comment]
比如集束400节点，同时发起请求，通过 apiserver 拉起 400个pod，确定能秒起，没有误差么？ @qwtsc

**Comment by qwtsc** [comment]
1. 不是通过apiserver拉起400个pod，pod是通过daemonset部署的，apiserver只是下发命令用，可以理解为对400个pod发起kubectl命令。 
2. 我记得之前[gaius-qi](https://github.com/gaius-qi)是不是已经处理过相关issue了，这个需要确认下。 
3. 日志这个可以再讨论是否有必要。
@gaius-qi @anjia0532

**Comment by anjia0532** [comment]
1. 我找找相关资料，我对这块并不是很了解，如果可以通过apiserver批量发送命令，且没有明显延迟的话，那就可以忽略 pod cronjob了
2. 之前跟百蓦沟通过，只是内部有dashboard，不能直接拿来开源，具体咋操作，还没沟通出方案，可以等周三例会上，沟通下
3. 之所以要加日志，考虑的是三个方面，
    - prometheus metrics 可能不完善，当然可以通过改代码来补全
    - 某些任务没起来就挂了，或者正在跑着挂了，此时采集metrics采不到，有缺失（当然可以通过减法来知道成功率，明确成功的/总任务数，其余的认为失败）
    - 用于分析压测的情况，尤其是长尾数据

@qwtsc

**Comment by anjia0532** [comment]
`/api/v1/proxy/nodes/{name}/pods/` 拉到所有pods 然后多线程调用  `/api/v1/proxy/nodes/{name}/exec `  执行命令？
